"""added new column to users

Revision ID: 0436a38ed804
Revises: 41e9912ba7cc
Create Date: 2024-12-15 15:05:03.050014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0436a38ed804'
down_revision = '41e9912ba7cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_blocked')
    # ### end Alembic commands ###
