"""added new column to order

Revision ID: 41e9912ba7cc
Revises: d156a3723305
Create Date: 2024-12-14 23:52:02.333564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e9912ba7cc'
down_revision = 'd156a3723305'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('lat_long', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'lat_long')
    # ### end Alembic commands ###
