"""changed columns

Revision ID: ad440bfee03d
Revises: 850cd10a37f7
Create Date: 2024-12-14 11:52:06.462137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad440bfee03d'
down_revision = '850cd10a37f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=150), nullable=True))
    op.alter_column('user', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('user', 'phone_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
