"""

Revision ID: b78b6ca7ec7f
Revises: bda4794e52ae
Create Date: 2025-01-02 18:06:26.222253

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b78b6ca7ec7f'
down_revision = 'bda4794e52ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    orderstatus_enum = postgresql.ENUM('PENDING', 'DELIVERED', 'CANCELLED', name='orderstatus', create_type=True)
    orderstatus_enum.create(op.get_bind(), checkfirst=True)
    op.drop_column('order', 'status')
    op.add_column('order', sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.Enum('PENDING', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
