"""

Revision ID: c8d17ad84374
Revises: 0436a38ed804
Create Date: 2024-12-27 14:53:07.993538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d17ad84374'
down_revision = '0436a38ed804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitem',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('total_price', sa.Numeric(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('lat_long', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_orderitem_order_id_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_orderitem_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderitem'))
    )
    op.drop_column('order', 'total_price')
    op.drop_column('order', 'lat_long')
    op.drop_column('order', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('lat_long', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('total_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_table('orderitem')
    # ### end Alembic commands ###
