"""added new column to cart model

Revision ID: d156a3723305
Revises: ad440bfee03d
Create Date: 2024-12-14 18:09:13.152481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd156a3723305'
down_revision = 'ad440bfee03d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'total_count')
    # ### end Alembic commands ###
